# Generated by Django 5.0.4 on 2024-05-03 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_certifications', '0001_initial'),
        ('app_general', '0003_alter_subscription_certification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='certification',
        ),
        migrations.AddField(
            model_name='subscription',
            name='certification_set',
            field=models.ManyToManyField(to='app_certifications.certification'),
        ),
    ]
