# Generated by Django 5.0.4 on 2024-07-08 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_standard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ItemTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('S', 'Sampling test'), ('R', 'Routine test')], default='S', max_length=1)),
                ('countries', models.ManyToManyField(related_name='specifications', to='app_standard.country')),
                ('item_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='app_standard.itemtest')),
            ],
        ),
        migrations.DeleteModel(
            name='MinimumStandard',
        ),
        migrations.DeleteModel(
            name='ScopeStandard',
        ),
    ]
