# Generated by Django 5.0.4 on 2024-07-08 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_standard', '0003_remove_specification_name_specification_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='relatemark',
            field=models.PositiveSmallIntegerField(choices=[(1, '⚈ Should be tested (If possible)'), (2, '⚉ Std.requirement (Must be tested)'), (3, '⚆ Std.requirement must be tested at external lab --> CCC'), (4, '⚇ Std.requirement which can select testing (Between Pressure and Refri. leakage test.)')], default=1),
        ),
    ]
