# Generated by Django 5.0.4 on 2024-07-08 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_standard', '0004_country_relatemark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='relatemark',
        ),
        migrations.CreateModel(
            name='CountrySpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relatemark', models.PositiveSmallIntegerField(choices=[(1, '⚈ Should be tested (If possible)'), (2, '⚉ Std.requirement (Must be tested)'), (3, '⚆ Std.requirement must be tested at external lab --> CCC'), (4, '⚇ Std.requirement which can select testing (Between Pressure and Refri. leakage test.)')], default=1)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_specifications', to='app_standard.country')),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_specifications', to='app_standard.specification')),
            ],
        ),
    ]
