# Generated by Django 5.0.4 on 2024-07-09 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_standard', '0005_remove_country_relatemark_countryspecification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specification',
            name='countries',
        ),
    ]
