# Generated by Django 5.0.4 on 2024-07-09 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_standard', '0006_remove_specification_countries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryspecification',
            name='relatemark',
            field=models.PositiveSmallIntegerField(choices=[(1, ' Should be tested (If possible)'), (2, ' Std.requirement (Must be tested)'), (3, ' Std.requirement must be tested at external lab --> CCC'), (4, ' Std.requirement which can select testing (Between Pressure and Refri. leakage test.)')], default=1),
        ),
    ]
