# Generated by Django 5.0.7 on 2024-07-20 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_standard', '0009_remove_specification_type_specification_test_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtest',
            name='no',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='specification',
            name='description',
            field=models.TextField(default='xxxxxxx', max_length=700),
        ),
    ]
