# Generated by Django 5.0.7 on 2024-07-23 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_standard', '0010_itemtest_no_alter_specification_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='countrytestrequirement',
            name='requirement',
            field=models.CharField(choices=[('1', 'Should be tested (If possible)'), ('2', 'Std.requirement (Must be tested)'), ('3', 'Std.requirement must be tested at external lab (CCC)'), ('4', 'Std.requirement which can select testing (Between Pressure and Refri. leakage test) (QCO)')], max_length=1),
        ),
    ]
