# Generated by Django 5.0.7 on 2024-08-13 00:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_standard', '0011_alter_country_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='description',
            field=ckeditor.fields.RichTextField(default='xxxxxxx', max_length=700),
        ),
    ]
