# Generated by Django 5.1.1 on 2024-10-21 04:17

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_standard', '0012_alter_specification_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequirementChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProductScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard', ckeditor.fields.RichTextField()),
                ('scope', models.TextField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_standard.country')),
            ],
        ),
        migrations.AlterField(
            model_name='countrytestrequirement',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_standard.requirementchoice'),
        ),
    ]
