# Generated by Django 5.1.1 on 2024-10-21 04:19

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_standard', '0013_requirementchoice_productscope_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productscope',
            name='scope',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='productscope',
            name='standard',
            field=models.TextField(),
        ),
    ]
