# Generated by Django 5.1.1 on 2024-10-21 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_standard', '0014_alter_productscope_scope_alter_productscope_standard'),
    ]

    operations = [
        migrations.AddField(
            model_name='specification',
            name='mandatory_voluntory',
            field=models.CharField(choices=[('Mandatory', 'Mandatory'), ('Voluntary', 'Voluntary'), ('N/A', 'N/A')], default='N/A', max_length=10),
        ),
    ]
