# Generated by Django 5.1.1 on 2024-10-22 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_standard', '0015_specification_mandatory_voluntory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='mandatory_voluntory',
            field=models.CharField(choices=[('Mandatory', 'N'), ('Voluntary', 'M'), ('N/A', 'N/A')], default='N/A', max_length=10),
        ),
        migrations.AlterField(
            model_name='specification',
            name='test_type',
            field=models.CharField(choices=[('S', 'S'), ('R', 'R')], default='R', max_length=1),
        ),
    ]
