# Generated by Django 5.0.7 on 2024-08-06 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Regulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regulation', models.CharField(max_length=350)),
                ('regulation_image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('mandatory_voluntory', models.CharField(choices=[('Mandatory', 'Mandatory'), ('Voluntary', 'Voluntary'), ('N/A', 'N/A')], max_length=10)),
                ('standard', models.CharField(blank=True, max_length=355, null=True)),
                ('effectivedate', models.TextField(blank=True, null=True)),
                ('MCP_action', models.TextField(blank=True, null=True)),
                ('scope', models.TextField(blank=True, null=True)),
                ('scope_image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('detail', models.TextField(blank=True, null=True)),
                ('detail_image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('by', models.CharField(max_length=255)),
                ('remark', models.CharField(max_length=255)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regulations', to='app_regulation.country')),
            ],
        ),
        migrations.CreateModel(
            name='Stakeholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('countries', models.ManyToManyField(related_name='stakeholders', to='app_regulation.country')),
            ],
        ),
    ]
