# Generated by Django 5.0.7 on 2024-08-07 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_regulation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regulation',
            old_name='MCP_action',
            new_name='action',
        ),
    ]
