# Generated by Django 5.0.7 on 2024-08-07 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_regulation', '0002_rename_mcp_action_regulation_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stakeholder',
            name='name',
        ),
    ]
