# Generated by Django 5.0.7 on 2024-08-14 04:00

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_regulation', '0006_alter_regulation_scope'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regulation',
            name='effectivedate',
        ),
        migrations.AddField(
            model_name='country',
            name='caution_threshold',
            field=models.IntegerField(default=180),
        ),
        migrations.AddField(
            model_name='country',
            name='critical_threshold',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='country',
            name='serious_threshold',
            field=models.IntegerField(default=120),
        ),
        migrations.AddField(
            model_name='regulation',
            name='effective_date',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='regulation',
            name='expire_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='regulation',
            name='status',
            field=models.CharField(choices=[('activating', 'Activating'), ('caution', 'Caution'), ('serious', 'Serious'), ('critical', 'Critical'), ('expired', 'Expired')], default='activating', max_length=10),
        ),
        migrations.AlterField(
            model_name='regulation',
            name='action',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regulation',
            name='by',
            field=ckeditor.fields.RichTextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='regulation',
            name='detail',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regulation',
            name='remark',
            field=ckeditor.fields.RichTextField(blank=True, max_length=255, null=True),
        ),
    ]
