# Generated by Django 5.0.7 on 2024-09-06 02:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_regulation', '0008_remove_stakeholder_countries_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regulation',
            name='detail_image_url',
        ),
        migrations.RemoveField(
            model_name='regulation',
            name='regulation_image_url',
        ),
        migrations.RemoveField(
            model_name='regulation',
            name='scope_image_url',
        ),
        migrations.AlterField(
            model_name='regulation',
            name='remark',
            field=ckeditor.fields.RichTextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='regulation',
            name='status',
            field=models.CharField(choices=[('caution', 'Caution'), ('serious', 'Serious'), ('critical', 'Critical'), ('overdue', 'Overdue'), ('finished', 'Finished'), ('inprogress', 'In Progress')], default='inprogress', max_length=10),
        ),
    ]
