# Generated by Django 5.1.1 on 2024-09-16 06:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_regulation', '0009_remove_regulation_detail_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regulation',
            name='remark',
            field=ckeditor.fields.RichTextField(blank=True, max_length=500000, null=True),
        ),
    ]
