# Generated by Django 5.1.1 on 2024-09-21 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(choices=[('app_certifications.tasks.send_weekly_email', 'Weekly Email Certifications'), ('app_regulation.tasks.send_weekly_email', 'Weekly Email Regulations')], max_length=255, unique=True)),
                ('day_of_week', models.CharField(help_text="Day of the week as a crontab format, e.g., 'monday', 'tuesday', or '*'.", max_length=9)),
                ('hour', models.PositiveIntegerField(help_text='Hour in 24-hour format')),
                ('minute', models.PositiveIntegerField(help_text='Minute')),
            ],
        ),
    ]
