# Generated by Django 5.1.1 on 2024-09-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_taskschedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskschedule',
            name='month',
            field=models.CharField(blank=True, help_text="Optional. Month as a crontab format, e.g., '1' for January, or '*' for every month.", max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='taskschedule',
            name='task_name',
            field=models.CharField(choices=[('app_certifications.tasks.send_weekly_email', 'Schedule Email Certifications'), ('app_regulation.tasks.send_weekly_email', 'Schedule Email Regulations')], max_length=255, unique=True),
        ),
    ]
