# Generated by Django 5.1.1 on 2024-09-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_taskschedule', '0002_taskschedule_month_alter_taskschedule_task_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskschedule',
            old_name='month',
            new_name='month_of_year',
        ),
        migrations.AddField(
            model_name='taskschedule',
            name='day_of_month',
            field=models.CharField(blank=True, help_text="Optional. Day of the month, e.g., '1', '15', or '*' for every day.", max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='taskschedule',
            name='day_of_week',
            field=models.CharField(blank=True, help_text="Optional. Day of the week as a crontab format, e.g., 'monday', 'tuesday', or '*' for every day.", max_length=9, null=True),
        ),
    ]
