# Generated by Django 5.1.1 on 2024-10-24 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_taskschedule', '0003_rename_month_taskschedule_month_of_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskschedule',
            name='send_by_email',
            field=models.EmailField(default='<siripannee.n@mcp.meap.com>', help_text='Email of the sender', max_length=254),
        ),
        migrations.AddField(
            model_name='taskschedule',
            name='send_by_name',
            field=models.CharField(default='Siripannee Nonesrivow', help_text='Name of the email sender', max_length=255),
        ),
    ]
