# Generated by Django 5.0.4 on 2024-07-04 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_certifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('caution_threshold', models.IntegerField(default=90)),
                ('serious_threshold', models.IntegerField(default=60)),
                ('critical_threshold', models.IntegerField(default=30)),
                ('image_relative_url', models.CharField(default='default.jpg', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='IndoorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OutdoorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StakeholderEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=60, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='certification',
            name='indoor_model_name',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='outdoor_model_name',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='remark',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='report_issue_date',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='report_no',
        ),
        migrations.AddField(
            model_name='certification',
            name='certificate_name',
            field=models.CharField(default='Please enter the certificate name. ', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='certification',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='app_certifications.country'),
        ),
        migrations.CreateModel(
            name='IndoorOutdoorPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indoor_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outdoor_pairs', to='app_certifications.indoormodel')),
                ('outdoor_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indoor_pairs', to='app_certifications.outdoormodel')),
            ],
        ),
        migrations.CreateModel(
            name='CertificateNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_no', models.CharField(max_length=255, unique=True)),
                ('certificate_no_link', models.CharField(blank=True, max_length=255, null=True)),
                ('issue_date', models.DateTimeField(blank=True, null=True)),
                ('expire_date', models.DateTimeField(blank=True, null=True)),
                ('report_issue_date', models.DateTimeField(blank=True, null=True)),
                ('report_no', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('activating', 'Activating'), ('caution', 'Caution'), ('serious', 'Serious'), ('critical', 'Critical'), ('expired', 'Expired')], default='activate', max_length=10)),
                ('remark', models.TextField(blank=True, null=True)),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_numbers', to='app_certifications.certification')),
                ('indoor_models', models.ManyToManyField(related_name='certificate_numbers', to='app_certifications.indoormodel')),
                ('indoor_outdoor_pairs', models.ManyToManyField(blank=True, related_name='certificate_numbers', to='app_certifications.indooroutdoorpair')),
                ('outdoor_models', models.ManyToManyField(related_name='certificate_numbers', to='app_certifications.outdoormodel')),
            ],
        ),
        migrations.AddField(
            model_name='country',
            name='stakeholders_email',
            field=models.ManyToManyField(related_name='countries', to='app_certifications.stakeholderemail'),
        ),
    ]
