# Generated by Django 5.0.7 on 2024-08-19 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_certifications', '0002_country_indoormodel_outdoormodel_stakeholderemail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatenumber',
            name='status',
            field=models.CharField(choices=[('activating', 'Activating'), ('caution', 'Caution'), ('serious', 'Serious'), ('critical', 'Critical'), ('expired', 'Expired')], default='activating', max_length=10),
        ),
    ]
