# Generated by Django 5.1.1 on 2024-09-20 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_certifications', '0004_alter_certificatenumber_remark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificatenumber',
            name='report_issue_date',
        ),
        migrations.RemoveField(
            model_name='certificatenumber',
            name='report_no',
        ),
        migrations.AlterField(
            model_name='certificatenumber',
            name='status',
            field=models.CharField(choices=[('activating', 'Activating'), ('caution', 'Caution'), ('serious', 'Serious'), ('critical', 'Critical'), ('expired', 'Expired'), ('discont', 'Discont')], default='activating', max_length=10),
        ),
    ]
