# Generated by Django 5.1.1 on 2024-09-20 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_certifications', '0005_remove_certificatenumber_report_issue_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificatenumber',
            name='indoor_outdoor_pairs',
        ),
        migrations.DeleteModel(
            name='IndoorOutdoorPair',
        ),
    ]
